
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UsersProvider } from '@/context/UserContext'
import { LoginProvider } from '@/context/LoginContext'
import { OrderProvider } from '@/context/OrderContext'
import { ProductsProvider } from '@/context/ProductContext'
import { LocalProfilesProvider } from '@/context/LocalProfileContext'
import { ScoresProvider } from '@/context/ScoreContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ScoresProvider>
        <LocalProfilesProvider>
        <ProductsProvider>
        <OrderProvider>
        <UsersProvider>
            <LoginProvider>
            {children}
            </LoginProvider>
        </UsersProvider>
        </OrderProvider>
        </ProductsProvider>
        </LocalProfilesProvider>
        </ScoresProvider>
      </body>
    </html>
  )
}