import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { LoginProvider } from "@/context/LoginContext";
import Navbar from "@/components/Navbar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Pedidos Crombie",
	description: "Generated by create next app",
};

export default function LoginLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<LoginProvider>
					<Navbar text="Pedidos Crombie - Bienvenido de vuelta!" />
					{children}
				</LoginProvider>
			</body>
		</html>
	);
}
