import { LocalProfilesProvider } from '@/context/LocalProfileContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ProductsProvider } from '@/context/ProductContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocalProfilesProvider>
          <ProductsProvider>
          {children}
          </ProductsProvider>
        </LocalProfilesProvider>
        
      </body>
    </html>
  )
}
