import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ProductsProvider } from "@/context/ProductContext";
import { LocalProfilesProvider } from "@/context/LocalProfileContext";
import { CartProvider } from "@/context/CartContext";
import { OrderProvider } from "@/context/OrderContext";
import { ScoresProvider } from "@/context/ScoreContext";
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Pedidos Crombie",
	description: "Generated by create next app",
};

export default function SellerLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<OrderProvider>
					<CartProvider>
						<LocalProfilesProvider>
							<ProductsProvider>
								<ScoresProvider>{children}</ScoresProvider>
							</ProductsProvider>
						</LocalProfilesProvider>
					</CartProvider>
				</OrderProvider>
			</body>
		</html>
	);
}
