import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ProductsProvider } from '@/context/ProductContext'
import { LocalProfilesProvider } from '@/context/LocalProfileContext'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocalProfilesProvider>
          <ProductsProvider>
          <Navbar text="Pedidos Crombie - Busca lo que quieras" />
          {children}
          </ProductsProvider>
        </LocalProfilesProvider>
        
      </body>
    </html>
  )
}