import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ProductsProvider } from "@/context/ProductContext";
import { LocalProfilesProvider } from "@/context/LocalProfileContext";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pedidos Crombie",
  description: "Generated by create next app",
};

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <LocalProfilesProvider>
          <ProductsProvider>
            {children}
          </ProductsProvider>
        </LocalProfilesProvider>
      </body>
    </html>
  );
}
